name: test-genres

on:
  pull_request:
    paths:
      - 'genre-service/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd genre-service && npm install && npm run test:ci
